<#
===========================================================================
 Eight Rock Workbench v5.0 - Windows installer (Section 9.1, Windows path)
 --------------------------------------------------------------------------
 Windows analog of deploy/install.sh. Installs and wires the pilot stack on
 Windows Server 2022 (or Windows 10/11) using NSSM + Caddy, per the spec's
 "Windows works with NSSM + Caddy for Windows" note.

 Installs: Python 3.12, uv, PostgreSQL 16, Caddy, NSSM. Creates the database,
 applies db/pilot_schema.sql, registers the Streamlit app as a Windows service
 bound to 127.0.0.1:8501, installs Caddy as a service for public HTTPS, and
 opens the Windows Firewall for 80/443.

 Run from an ELEVATED PowerShell (Run as Administrator):
   cd C:\WORKBENCH_V5
   Set-ExecutionPolicy -Scope Process Bypass -Force
   .\deploy\windows\install.ps1 -Domain workbench.eight-rock.com

 Idempotent where practical. Prints remaining manual steps at the end.
===========================================================================
#>
[CmdletBinding()]
param(
    [string]$Domain  = "workbench.eight-rock.com",
    [string]$AppDir  = "C:\WORKBENCH_V5",      # app lives on LOCAL disk - never OneDrive (Section 9.2)
    [string]$DbName  = "workbench",
    [string]$DbUser  = "workbench"
)

$ErrorActionPreference = "Stop"
function Step($m){ Write-Host "`n>> $m" -ForegroundColor Yellow }
function Have($c){ [bool](Get-Command $c -ErrorAction SilentlyContinue) }

# --- admin check ----------------------------------------------------------
if (-not ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()
        ).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    throw "Run this from an elevated PowerShell (Run as Administrator)."
}

# --- 0. package manager (winget preferred; choco fallback notice) ----------
$useWinget = Have winget
if (-not $useWinget) {
    Write-Warning "winget not found. Install 'App Installer' from the Microsoft Store, or install the components manually (see deploy/windows/README.md), then re-run."
}

function Winget-Install($id){
    if ($useWinget) {
        Step "winget install $id"
        winget install --id $id -e --silent --accept-source-agreements --accept-package-agreements
    } else {
        Write-Warning "Skipping $id (winget unavailable) - install it manually per README."
    }
}

# --- 1. Python 3.12 + uv ---------------------------------------------------
if (-not (Have python)) { Winget-Install "Python.Python.3.12" }
if (-not (Have uv)) {
    Step "Installing uv"
    powershell -NoProfile -ExecutionPolicy Bypass -Command "irm https://astral.sh/uv/install.ps1 | iex"
    $env:Path = "$env:USERPROFILE\.local\bin;$env:Path"
}

# --- 2. PostgreSQL 16 ------------------------------------------------------
if (-not (Have psql)) { Winget-Install "PostgreSQL.PostgreSQL.16" }
# Locate psql if not on PATH yet
$pg = Get-ChildItem "C:\Program Files\PostgreSQL\16\bin\psql.exe" -ErrorAction SilentlyContinue
if ($pg) { $env:Path = "C:\Program Files\PostgreSQL\16\bin;$env:Path" }

# --- 3. Caddy + NSSM -------------------------------------------------------
if (-not (Have caddy)) { Winget-Install "CaddyServer.Caddy" }
if (-not (Have nssm))  { Winget-Install "NSSM.NSSM" }

# --- 4. Database + schema --------------------------------------------------
Step "Creating database '$DbName' and role '$DbUser'"
$DbPass = -join ((48..57)+(65..90)+(97..122) | Get-Random -Count 32 | ForEach-Object {[char]$_})
$env:PGPASSWORD = Read-Host "Enter the postgres superuser password (set during PostgreSQL install)"
$createSql = @"
DO `$`$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='$DbUser') THEN
    CREATE ROLE $DbUser LOGIN PASSWORD '$DbPass';
  END IF;
END `$`$;
SELECT 'CREATE DATABASE $DbName OWNER $DbUser'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname='$DbName')\gexec
"@
$createSql | psql -U postgres -h 127.0.0.1 -v ON_ERROR_STOP=1

$EnvFile = Join-Path $AppDir ".env"
if (-not (Test-Path $EnvFile)) {
@"
# Generated by install.ps1 - secrets, DO NOT COMMIT (Section 9.1).
DATABASE_URL=postgresql://$DbUser`:$DbPass@127.0.0.1:5432/$DbName
ER_STORAGE_BACKEND=local
ER_AUTH_BACKEND=oidc
APP_VERSION=v5.0-pilot
"@ | Set-Content -Encoding ASCII $EnvFile
    Write-Host "Wrote $EnvFile (gitignored)."
} else {
    Write-Host "Existing $EnvFile kept."
}

Step "Applying pilot schema"
$env:PGPASSWORD = $DbPass
psql -U $DbUser -h 127.0.0.1 -d $DbName -v ON_ERROR_STOP=1 -f (Join-Path $AppDir "db\pilot_schema.sql")

# --- 5. Python deps --------------------------------------------------------
Step "Installing Python dependencies (uv sync)"
Push-Location $AppDir
try { uv sync --frozen } catch { uv sync }
Pop-Location

# --- 6. Streamlit services (blue-green) via NSSM ---------------------------
# Delegated to install-lan-service.ps1 so there is ONE service-naming scheme.
# This script used to register a single service called "Workbench" on 8501,
# which collided with the WorkbenchBlue that install-lan-service.ps1 puts on
# the same port, and which deploy-swap.ps1 would never find.
Step "Registering WorkbenchBlue (8501) + WorkbenchGreen (8502) on localhost"
$lan = Join-Path $AppDir "deploy\windows\install-lan-service.ps1"
# Retire the pre-blue-green service if this box was installed before the split.
cmd /c "nssm stop Workbench" 2>$null
cmd /c "nssm remove Workbench confirm" 2>$null
# Blue prompts for the passcode; green reuses it, so the pair asks once.
& powershell -NoProfile -ExecutionPolicy Bypass -File $lan `
    -AppDir $AppDir -Name "WorkbenchBlue" -Port 8501 -BindAddress "127.0.0.1"
if ($LASTEXITCODE -ne 0) { throw "Failed to install WorkbenchBlue" }
& powershell -NoProfile -ExecutionPolicy Bypass -File $lan `
    -AppDir $AppDir -Name "WorkbenchGreen" -Port 8502 -BindAddress "127.0.0.1" -KeepPasscode
if ($LASTEXITCODE -ne 0) { throw "Failed to install WorkbenchGreen" }

# --- 7. Caddy as a service -------------------------------------------------
Step "Configuring Caddy for $Domain"
$caddyfileSrc = Join-Path $AppDir "deploy\windows\Caddyfile"
$caddyfile    = Join-Path $AppDir "deploy\windows\Caddyfile.active"
(Get-Content $caddyfileSrc) -replace "workbench.eight-rock.com", $Domain `
    -replace "C:\\WORKBENCH_V5", ($AppDir -replace '\\','\\') | Set-Content $caddyfile
# Caddy can install itself as a Windows service (v2.6+). If unavailable, use NSSM.
cmd /c "nssm stop Caddy" 2>$null; cmd /c "nssm remove Caddy confirm" 2>$null
$caddyPath = (Get-Command caddy).Source
nssm install Caddy $caddyPath "run --config `"$caddyfile`" --adapter caddyfile"
nssm set Caddy AppDirectory $AppDir
nssm set Caddy Start SERVICE_AUTO_START
nssm start Caddy

# --- 8. Windows Firewall ---------------------------------------------------
Step "Opening Windows Firewall for public 80/443 (8501 stays localhost)"
netsh advfirewall firewall add rule name="Workbench HTTP"  dir=in action=allow protocol=TCP localport=80  | Out-Null
netsh advfirewall firewall add rule name="Workbench HTTPS" dir=in action=allow protocol=TCP localport=443 | Out-Null

# --- done ------------------------------------------------------------------
Write-Host "`n==================== Install complete ====================" -ForegroundColor Green
@"
  Workbench v5.0 pilot stack installed on Windows.
    Domain    : https://$Domain
    App dir   : $AppDir   (local disk - never OneDrive, Section 9.2)
    App svc   : nssm status Workbench   |   logs in $AppDir\logs
    Proxy svc : nssm status Caddy
    Database  : $DbName   (credentials in $AppDir\.env - gitignored)

  MANUAL steps remaining:
    1. Point DNS A-record $Domain -> this server's reserved public IP.
    2. Port-forward public 80 + 443 to this box on your router.
    3. Fill in the [auth] OIDC block in .streamlit\secrets.toml (Auth0/Entra, Section 9.4).
    4. Schedule deploy\windows\backup.ps1 nightly (Task Scheduler).
    5. First login auto-promotes to admin; approve subsequent users (FR-9.4.3).
"@ | Write-Host
