<#
===========================================================================
 Eight Rock Workbench v5.0 - database setup (Windows). Run as Administrator.
 --------------------------------------------------------------------------
 Creates the `workbench` role + database, applies db/pilot_schema.sql, and
 writes .env with a freshly generated password, WITHOUT needing the postgres
 superuser password. It does this by briefly switching local authentication to
 "trust" (localhost only), doing the setup, then restoring the original config
 and restarting the service. Idempotent: safe to re-run.

 Run from an ELEVATED PowerShell (Run as Administrator):
   cd C:\WORKBENCH_V5
   Set-ExecutionPolicy -Scope Process Bypass -Force
   .\deploy\windows\setup-db.ps1
===========================================================================
#>
[CmdletBinding()]
param(
    [string]$PgVersion = "16",
    [string]$DbName    = "workbench",
    [string]$DbUser    = "workbench",
    [string]$AppDir    = "C:\WORKBENCH_V5"
)
$ErrorActionPreference = "Stop"
function Step($m){ Write-Host ("`n>> " + $m) -ForegroundColor Yellow }

# admin check
if (-not ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()
        ).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    throw "Run this from an elevated PowerShell (Run as Administrator)."
}

$PgBase = "C:\Program Files\PostgreSQL\$PgVersion"
$PgBin  = Join-Path $PgBase "bin"
$PgData = Join-Path $PgBase "data"
$psql   = Join-Path $PgBin  "psql.exe"
if (-not (Test-Path $psql)) { throw ("psql not found at " + $psql + " - is PostgreSQL " + $PgVersion + " installed?") }

$svc = Get-Service -Name "postgresql*$PgVersion*" -ErrorAction SilentlyContinue | Select-Object -First 1
if (-not $svc) { $svc = Get-Service -Name "postgresql*" -ErrorAction SilentlyContinue | Select-Object -First 1 }
if (-not $svc) { throw "PostgreSQL Windows service not found." }
Step ("Using service '" + $svc.Name + "', data dir '" + $PgData + "'")

$hba = Join-Path $PgData "pg_hba.conf"
$bak = Join-Path $PgData "pg_hba.conf.8rw-bak"

# strong random password for the workbench role
$DbPass = -join ((48..57)+(65..90)+(97..122) | Get-Random -Count 32 | ForEach-Object {[char]$_})

try {
    Step "Temporarily trusting localhost connections for setup"
    Copy-Item $hba $bak -Force
    $trust = "# --- temporary 8RW setup (auto-removed) ---`r`n" +
             "host all all 127.0.0.1/32 trust`r`n" +
             "host all all ::1/128 trust`r`n"
    Set-Content -Path $hba -Value ($trust + (Get-Content $hba -Raw)) -Encoding ASCII
    Restart-Service $svc.Name
    Start-Sleep -Seconds 4

    Step "Creating role '$DbUser' and database '$DbName'"
    $create = @"
DO `$`$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='$DbUser') THEN
    CREATE ROLE $DbUser LOGIN PASSWORD '$DbPass';
  ELSE
    ALTER ROLE $DbUser PASSWORD '$DbPass';
  END IF;
END `$`$;
SELECT 'CREATE DATABASE $DbName OWNER $DbUser'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname='$DbName')\gexec
"@
    $create | & $psql -U postgres -h 127.0.0.1 -v ON_ERROR_STOP=1 -q

    Step "Applying pilot schema (db\pilot_schema.sql)"
    & $psql -U $DbUser -h 127.0.0.1 -d $DbName -v ON_ERROR_STOP=1 -q -f (Join-Path $AppDir "db\pilot_schema.sql")
}
finally {
    if (Test-Path $bak) {
        Step "Restoring original authentication config"
        Copy-Item $bak $hba -Force
        Remove-Item $bak -Force
        Restart-Service $svc.Name
        Start-Sleep -Seconds 4
    }
}

Step "Writing $AppDir\.env (gitignored) - preserving existing keys"
$envFile = Join-Path $AppDir ".env"
# UPSERT, don't clobber. The prior version wrote a fresh 3-line .env with
# Set-Content, which DESTROYED every other key already there - the Anthropic
# API key, the live skiptrace provider keys (Cobalt/BatchData/Trestle/Apollo),
# ER_APP_PASSCODE, etc. Re-running setup for the DB must never nuke unrelated
# secrets. So: back the file up once, keep every line we don't manage, and
# refresh only our three managed keys.
$managed = [ordered]@{
    "DATABASE_URL"       = "postgresql://$DbUser`:$DbPass@127.0.0.1:5432/$DbName"
    "ER_STORAGE_BACKEND" = "local"
    "APP_VERSION"        = "v5.0-pilot"
}
$lines = @()
if (Test-Path $envFile) {
    Copy-Item $envFile ($envFile + ".bak") -Force
    foreach ($line in (Get-Content $envFile)) {
        $key = ($line -split "=", 2)[0].Trim()
        if ($managed.Keys -notcontains $key) { $lines += $line }
    }
} else {
    $lines += "# Generated by setup-db.ps1 - secrets, DO NOT COMMIT."
}
foreach ($k in $managed.Keys) { $lines += ($k + "=" + $managed[$k]) }
Set-Content -Path $envFile -Value $lines -Encoding ASCII

# quick verification
$env:PGPASSWORD = $DbPass
$presets = (& $psql -U $DbUser -h 127.0.0.1 -d $DbName -tAc "select count(*) from role_presets").Trim()
Write-Host "`n==================== Database ready ====================" -ForegroundColor Green
Write-Host ("  Database : " + $DbName + "   (owner: " + $DbUser + ")")
Write-Host ("  Schema   : applied - role_presets rows = " + $presets + " (expected 18)")
Write-Host ("  Conn     : written to " + $envFile)
Write-Host  "  Next     : uv sync   (installs the app's Python dependencies)"
