<#
===========================================================================
 Eight Rock Workbench v5.0 - backup role setup (Windows). Run as Administrator.
 --------------------------------------------------------------------------
 The nightly pg_dump fails as the app's `workbench` role because FORCE ROW
 LEVEL SECURITY applies to the table owner too (that is WHY tenant isolation
 holds - see CLAUDE.md). A complete dump needs a dedicated read-only role that
 can bypass RLS. This script creates it WITHOUT you typing the postgres
 password, using the exact trust-flip trick setup-db.ps1 already uses:
 briefly trust localhost, create the role, restore the config, restart.

 It then RUNS one backup to prove the whole path works end to end before
 declaring success (the delivery-channel-is-the-product rule).

 Run from an ELEVATED PowerShell (Run as Administrator), or just double-click
 setup-backup.bat:
   cd C:\WORKBENCH_V5
   Set-ExecutionPolicy -Scope Process Bypass -Force
   .\deploy\windows\setup-backup.ps1
 Idempotent: safe to re-run (rotates the role password each time).
===========================================================================
#>
[CmdletBinding()]
param(
    [string]$PgVersion = "16",
    [string]$DbName    = "workbench",
    [string]$BackupUser = "backup_reader",
    [string]$AppDir    = "C:\WORKBENCH_V5"
)
$ErrorActionPreference = "Stop"
function Step($m){ Write-Host ("`n>> " + $m) -ForegroundColor Yellow }

if (-not ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()
        ).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    throw "Run this from an elevated PowerShell (Run as Administrator)."
}

$PgBase = "C:\Program Files\PostgreSQL\$PgVersion"
$PgBin  = Join-Path $PgBase "bin"
$PgData = Join-Path $PgBase "data"
$psql   = Join-Path $PgBin  "psql.exe"
if (-not (Test-Path $psql)) { throw ("psql not found at " + $psql + " - is PostgreSQL " + $PgVersion + " installed?") }

$svc = Get-Service -Name "postgresql*$PgVersion*" -ErrorAction SilentlyContinue | Select-Object -First 1
if (-not $svc) { $svc = Get-Service -Name "postgresql*" -ErrorAction SilentlyContinue | Select-Object -First 1 }
if (-not $svc) { throw "PostgreSQL Windows service not found." }
Step ("Using service '" + $svc.Name + "', data dir '" + $PgData + "'")

$hba = Join-Path $PgData "pg_hba.conf"
$bak = Join-Path $PgData "pg_hba.conf.8rw-backuprole-bak"

# strong random password for the backup role (ASCII alphanumerics only, so it
# is safe both in a .env line and in a connection URI - no escaping needed)
$BkPass = -join ((48..57)+(65..90)+(97..122) | Get-Random -Count 40 | ForEach-Object {[char]$_})

try {
    Step "Temporarily trusting localhost connections for setup"
    Copy-Item $hba $bak -Force
    $trust = "# --- temporary 8RW backup-role setup (auto-removed) ---`r`n" +
             "host all all 127.0.0.1/32 trust`r`n" +
             "host all all ::1/128 trust`r`n"
    Set-Content -Path $hba -Value ($trust + (Get-Content $hba -Raw)) -Encoding ASCII
    Restart-Service $svc.Name
    Start-Sleep -Seconds 4

    Step "Creating read-only backup role '$BackupUser' (BYPASSRLS + read-all)"
    $create = @"
DO `$`$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='$BackupUser') THEN
    CREATE ROLE $BackupUser LOGIN PASSWORD '$BkPass' BYPASSRLS;
  ELSE
    ALTER ROLE $BackupUser LOGIN PASSWORD '$BkPass' BYPASSRLS;
  END IF;
END `$`$;
GRANT pg_read_all_data TO $BackupUser;
GRANT CONNECT ON DATABASE $DbName TO $BackupUser;
"@
    $create | & $psql -U postgres -h 127.0.0.1 -v ON_ERROR_STOP=1 -q
}
finally {
    if (Test-Path $bak) {
        Step "Restoring original authentication config"
        Copy-Item $bak $hba -Force
        Remove-Item $bak -Force
        Restart-Service $svc.Name
        Start-Sleep -Seconds 4
    }
}

Step "Writing ER_BACKUP_DATABASE_URL to $AppDir\.env (upsert - other keys preserved)"
$envFile = Join-Path $AppDir ".env"
$managedKey = "ER_BACKUP_DATABASE_URL"
$managedVal = "postgresql://$BackupUser`:$BkPass@127.0.0.1:5432/$DbName"
$lines = @()
if (Test-Path $envFile) {
    Copy-Item $envFile ($envFile + ".bak") -Force
    foreach ($line in (Get-Content $envFile)) {
        $key = ($line -split "=", 2)[0].Trim()
        if ($key -ne $managedKey) { $lines += $line }
    }
} else {
    $lines += "# Generated by setup-backup.ps1 - secrets, DO NOT COMMIT."
}
$lines += ($managedKey + "=" + $managedVal)
Set-Content -Path $envFile -Value $lines -Encoding ASCII

Step "Proving the path: running one backup now"
Push-Location $AppDir
try {
    $uv = Join-Path $env:USERPROFILE ".local\bin\uv.exe"
    if (-not (Test-Path $uv)) { $uv = "uv" }
    & $uv run python scripts\run_backup.py
    $code = $LASTEXITCODE
} finally {
    Pop-Location
}

if ($code -eq 0) {
    Write-Host "`n==================== Backup role ready ====================" -ForegroundColor Green
    Write-Host ("  Role     : " + $BackupUser + " (read-only, BYPASSRLS)")
    Write-Host ("  Conn     : ER_BACKUP_DATABASE_URL written to " + $envFile)
    Write-Host  "  Proof    : a dump ran just now (see the [backup] line above)."
    Write-Host  "  From now : every autopilot cycle backs up automatically."
} else {
    Write-Host "`nBackup role created, but the test dump did not report success." -ForegroundColor Red
    Write-Host "Read the [backup] line above and send it to Claude."
    exit 1
}
