@echo off
setlocal EnableDelayedExpansion
REM ===================================================================
REM  "Internal Server Error" on /oauth2callback - find out why.
REM
REM  This exact symptom was root-caused on 2026-08-10: Caddy fronts TWO
REM  app instances (8501 blue / 8502 green). The OAuth `state` is set in
REM  memory on whichever instance served the login redirect. If the
REM  callback lands on the OTHER instance, Authlib raises
REM  MismatchingStateError and Streamlit returns a 500. The fix is
REM  session affinity - `lb_policy cookie er_upstream` - which pins the
REM  whole handshake to one instance.
REM
REM  That fix lives in the repo's Caddyfile, but the file Caddy actually
REM  RUNS is Caddyfile.active, generated by install-caddy.ps1. If that
REM  was generated before the fix, the live config still has no affinity.
REM
REM  A second way to get the same 500: Caddy is told about two upstreams
REM  but only one is actually running, so some requests are routed to a
REM  dead port.
REM
REM  Read-only. Prints no secret VALUES and no file paths - key names and
REM  present/missing only.
REM ===================================================================
cd /d "%~dp0"
title Why is sign-in failing?

echo ============================================================
echo  1. WHICH APP INSTANCES ARE ACTUALLY UP
echo ============================================================
set "UP8501="
set "UP8502="
netstat -ano | findstr /r /c:":8501 .*LISTENING" >nul 2>&1 && set "UP8501=1"
netstat -ano | findstr /r /c:":8502 .*LISTENING" >nul 2>&1 && set "UP8502=1"
if defined UP8501 (echo   8501 blue : LISTENING) else (echo   8501 blue : DOWN)
if defined UP8502 (echo   8502 green: LISTENING) else (echo   8502 green: DOWN)
if not defined UP8501 if not defined UP8502 (
  echo.
  echo   Neither instance is up. Caddy has nothing to forward to, so
  echo   every request 500s. Start the app first, then retry sign-in.
)
echo.

echo ============================================================
echo  2. THE CONFIG CADDY IS ACTUALLY RUNNING
echo ============================================================
set "ACT=deploy\windows\Caddyfile.active"
if not exist "%ACT%" (
  echo   Caddyfile.active does NOT exist - Caddy was never configured
  echo   from this repo. Run: deploy\windows\install-caddy.ps1
  goto :logs
)
set "HASAFFINITY="
findstr /c:"lb_policy cookie" "%ACT%" >nul 2>&1 && set "HASAFFINITY=1"
if defined HASAFFINITY (
  echo   Session affinity: PRESENT ^(lb_policy cookie^)
) else (
  echo   Session affinity: **MISSING** - this is the known cause of the
  echo   Internal Server Error on /oauth2callback.
  echo.
  echo   FIX ^(pick one^):
  echo     powershell -ExecutionPolicy Bypass -File deploy\windows\install-caddy.ps1
  echo     ...which regenerates the active config and hot-reloads Caddy.
)
set "TWOUP="
findstr /c:"8502" "%ACT%" >nul 2>&1 && set "TWOUP=1"
if defined TWOUP if not defined UP8502 (
  echo.
  echo   MISMATCH: the live config forwards to 8502, but nothing is
  echo   listening there. Requests routed to green will fail. Either
  echo   start the green instance, or regenerate the config for a
  echo   single instance.
)

:logs
echo.
echo ============================================================
echo  3. WHAT THE ERROR LOG SAYS  ^(the authoritative answer^)
echo ============================================================
set "FOUNDLOG="
for %%F in (logs\service-*-err.log logs\service-*-out.log) do (
  if exist "%%F" (
    set "FOUNDLOG=1"
    echo   --- %%~nxF ---
    powershell -NoProfile -Command ^
      "Select-String -Path '%%F' -Pattern 'MismatchingState|CSRF|oauth2callback|Authlib|Traceback|Error' | Select-Object -Last 6 | ForEach-Object { '     ' + $_.Line.Trim() }" 2>nul
  )
)
if not defined FOUNDLOG (
  echo   No service logs found - the app is running from a console
  echo   window rather than the blue/green services. The traceback is
  echo   in THAT window; scroll it and look for the last Traceback.
  echo   'MismatchingStateError: CSRF Warning! State not equal' confirms
  echo   the session-affinity cause above.
)

echo.
echo ============================================================
echo  4. AUTH CONFIG COMPLETENESS  ^(names only, never values^)
echo ============================================================
set "SEC=.streamlit\secrets.toml"
if not exist "%SEC%" (
  echo   secrets.toml is MISSING - sign-in cannot work at all.
  goto :verdict
)
findstr /r /c:"^\[auth\]" "%SEC%" >nul 2>&1 && (echo   [auth] block: present) || echo   [auth] block: **MISSING**
for %%K in (redirect_uri cookie_secret client_id client_secret server_metadata_url) do (
  findstr /r /c:"^ *%%K" "%SEC%" >nul 2>&1 && (echo     %%K: set) || echo     %%K: **MISSING**
)
echo.
echo   All five must sit directly under a FLAT [auth] block - st.login^(^)
echo   reads them there and nowhere else. A nested sub-table looks valid
echo   and silently fails.

:verdict
echo.
echo ============================================================
echo  5. FASTEST WAY BACK IN
echo ============================================================
echo   a^) Retry the sign-in once or twice. With no affinity the failure
echo      is a coin flip - a retry that lands on the same instance
echo      succeeds, which is why this looks intermittent.
echo   b^) If section 2 says affinity is MISSING, run install-caddy.ps1.
echo      That is the actual fix, not a workaround.
echo   c^) If only one instance is up, reaching it directly on the LAN
echo      ^(port 8501^) takes Caddy out of the path entirely.
echo.
pause
