"""Excel workbook export for a single deal — Summary · Returns · Rent Roll.

Brian's first-user feedback (2026-08): "download to Excel — they have letters
and memos already [the Artifact Engine Word docs], but they want the *numbers*
in a spreadsheet they can slice." This builds a deterministic, no-API workbook
straight from the same DealState + cash-flow projection the Exec Summary tab
already computes, so the download always matches what's on screen.

Deliberately deterministic (unlike the LLM Artifact Engine): a spreadsheet is a
model, not prose. The three sheets are:

  1. **Summary**   — property identity, headline metrics, verdict + rationale.
  2. **Returns**   — the 5-year cash-flow table row-for-row, the exit block,
                     and the IRR / equity-multiple line.
  3. **Rent Roll** — the parsed unit rows from `sources["rentRoll"]` when a
                     rent roll has been ingested; otherwise a single note row.

`build_workbook_bytes` returns the `.xlsx` as bytes so the caller can hand it
straight to `st.download_button` — nothing is written to disk here.
"""

from __future__ import annotations

from io import BytesIO
from typing import Any

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.worksheet import Worksheet

import config

# Eight Rock brand accent for header fills (openpyxl wants ARGB, no '#').
_ACCENT = config.COLORS.get("ac", "#C8900A").lstrip("#")
_HEADER_FILL = PatternFill("solid", fgColor=f"FF{_ACCENT}")
_HEADER_FONT = Font(bold=True, color="FFFFFFFF")
_LABEL_FONT = Font(bold=True)
_TITLE_FONT = Font(bold=True, size=14)

_MONEY = "#,##0"
_MONEY2 = "#,##0.00"
_PCT = "0.0%"
_MULT = "0.00\"x\""


def _title(ws: Worksheet, text: str) -> None:
    ws["A1"] = text
    ws["A1"].font = _TITLE_FONT


def _header_row(ws: Worksheet, row: int, labels: list[str]) -> None:
    for col, label in enumerate(labels, start=1):
        cell = ws.cell(row=row, column=col, value=label)
        cell.fill = _HEADER_FILL
        cell.font = _HEADER_FONT
        cell.alignment = Alignment(horizontal="center")


def _kv(ws: Worksheet, row: int, label: str, value: Any,
        num_fmt: str | None = None) -> None:
    ws.cell(row=row, column=1, value=label).font = _LABEL_FONT
    cell = ws.cell(row=row, column=2, value=value)
    if num_fmt is not None and value is not None:
        cell.number_format = num_fmt


def _autosize(ws: Worksheet, widths: dict[int, int]) -> None:
    for col, width in widths.items():
        ws.column_dimensions[get_column_letter(col)].width = width


# ---------------------------------------------------------------------------
# Sheet builders
# ---------------------------------------------------------------------------

def _build_summary_sheet(ws: Worksheet, prop: dict[str, Any],
                         data: dict[str, Any]) -> None:
    ws.title = "Summary"
    deal = data["deal"]
    verdict = data["verdict"]
    tight = data.get("tightened")
    shown_verdict = tight.verdict if tight is not None else verdict.verdict

    _title(ws, f"{prop.get('name', '—')} — Executive Summary")

    r = 3
    _kv(ws, r, "Property", prop.get("name")); r += 1
    _kv(ws, r, "Address", prop.get("address")); r += 1
    _kv(ws, r, "City", prop.get("city")); r += 1
    _kv(ws, r, "State", prop.get("state") or "VA"); r += 1
    _kv(ws, r, "Units", prop.get("units")); r += 1
    _kv(ws, r, "Year built", prop.get("year_built")); r += 1
    _kv(ws, r, "Recommendation", shown_verdict); r += 2

    ws.cell(row=r, column=1, value="Key metrics").font = _LABEL_FONT
    r += 1
    _kv(ws, r, "Asking price", deal.pp, _MONEY); r += 1
    _kv(ws, r, "Price per unit", data["ppu"], _MONEY); r += 1
    _kv(ws, r, "NOI (in-place)", deal.noi, _MONEY); r += 1
    _kv(ws, r, "Cap rate", data["cap"], _PCT); r += 1
    _kv(ws, r, "DSCR", data["dscr"], _MULT); r += 1
    _kv(ws, r, "Cash-on-cash (Y1)", data["coc"], _PCT); r += 1
    _kv(ws, r, "LP IRR", data["lp_irr"], _PCT); r += 1
    _kv(ws, r, "Project IRR", data["project_irr"], _PCT); r += 1
    _kv(ws, r, "LP equity multiple", data["equity_multiple"], _MULT); r += 2

    ws.cell(row=r, column=1, value="Rationale").font = _LABEL_FONT
    r += 1
    for line in verdict.rationale:
        ws.cell(row=r, column=1, value=f"• {line}")
        r += 1
    if tight is not None:
        for line in tight.rationale:
            ws.cell(row=r, column=1, value=f"⚠ {line}")
            r += 1

    r += 1
    ws.cell(row=r, column=1,
            value=f"Generated by Eight Rock Workbench {config.WORKBENCH_VERSION}"
            ).font = Font(italic=True, color="FF5A6478")

    _autosize(ws, {1: 22, 2: 40})


def _build_returns_sheet(ws: Worksheet, data: dict[str, Any]) -> None:
    ws.title = "Returns"
    cf = data["cf"]

    _title(ws, "5-Year Cash Flow")

    cols = ["Year", "GPR", "Vacancy loss", "EGI", "Expenses", "NOI",
            "AM fee", "NOI after AM", "Debt service", "Cash flow", "CoC"]
    hdr = 3
    _header_row(ws, hdr, cols)
    money_cols = list(range(2, 11))     # GPR .. Cash flow
    for i, row in enumerate(cf.rows):
        r = hdr + 1 + i
        ws.cell(row=r, column=1, value=row.year)
        ws.cell(row=r, column=2, value=row.gpr)
        ws.cell(row=r, column=3, value=-row.vacancy_loss)
        ws.cell(row=r, column=4, value=row.egi)
        ws.cell(row=r, column=5, value=-row.expenses)
        ws.cell(row=r, column=6, value=row.noi)
        ws.cell(row=r, column=7, value=-row.am_fee)
        ws.cell(row=r, column=8, value=row.noi_after_am)
        ws.cell(row=r, column=9, value=-row.debt_service)
        ws.cell(row=r, column=10, value=row.cash_flow)
        coc_cell = ws.cell(row=r, column=11, value=row.coc)
        coc_cell.number_format = _PCT
        for col in money_cols:
            ws.cell(row=r, column=col).number_format = _MONEY

    # Exit + returns block below the table.
    r = hdr + 1 + len(cf.rows) + 1
    ws.cell(row=r, column=1, value="Exit & returns").font = _LABEL_FONT
    r += 1
    _kv(ws, r, "Exit NOI", cf.exit_noi, _MONEY); r += 1
    _kv(ws, r, "Exit proceeds (gross)", cf.exit_proceeds_gross, _MONEY); r += 1
    _kv(ws, r, "Loan payoff at exit", -cf.exit_loan_payoff, _MONEY); r += 1
    _kv(ws, r, "Exit proceeds (net)", cf.exit_proceeds_net, _MONEY); r += 1
    _kv(ws, r, "Equity raise", data["deal"].equity_raise, _MONEY); r += 1
    _kv(ws, r, "LP IRR", data["lp_irr"], _PCT); r += 1
    _kv(ws, r, "Project IRR", data["project_irr"], _PCT); r += 1
    _kv(ws, r, "LP equity multiple", data["equity_multiple"], _MULT); r += 1

    _autosize(ws, {1: 20, 2: 15, 3: 14, 4: 15, 5: 14, 6: 15,
                   7: 12, 8: 15, 9: 14, 10: 15, 11: 8})


def _build_rent_roll_sheet(ws: Worksheet,
                           sources: dict[str, Any] | None) -> None:
    ws.title = "Rent Roll"
    _title(ws, "Rent Roll")

    rent_roll = (sources or {}).get("rentRoll") or {}
    units = rent_roll.get("units") or []
    if not units:
        ws.cell(row=3, column=1,
                value="No rent roll ingested for this property yet. "
                      "Upload a rent roll on the Documents tab to populate "
                      "this sheet.")
        _autosize(ws, {1: 70})
        return

    src = rent_roll.get("file")
    date = rent_roll.get("date")
    if src or date:
        ws.cell(row=2, column=1,
                value=f"Source: {src or '—'}   ·   As of: {date or '—'}"
                ).font = Font(italic=True, color="FF5A6478")

    cols = ["Unit", "Type", "Status", "Tenant", "SqFt",
            "Market rent", "Actual rent", "Move-in", "Lease exp"]
    hdr = 4
    _header_row(ws, hdr, cols)
    for i, u in enumerate(units):
        r = hdr + 1 + i
        ws.cell(row=r, column=1, value=u.get("unit"))
        ws.cell(row=r, column=2, value=u.get("unitType"))
        ws.cell(row=r, column=3, value=u.get("status"))
        ws.cell(row=r, column=4, value=u.get("tenant"))
        ws.cell(row=r, column=5, value=u.get("sqft"))
        mr = ws.cell(row=r, column=6, value=u.get("marketRent"))
        ar = ws.cell(row=r, column=7, value=u.get("actualRent"))
        mr.number_format = _MONEY
        ar.number_format = _MONEY
        ws.cell(row=r, column=8, value=u.get("moveIn"))
        ws.cell(row=r, column=9, value=u.get("leaseExp"))

    # Totals row from the parsed summary (already computed at ingest).
    summary = rent_roll.get("summary") or {}
    r = hdr + 1 + len(units) + 1
    ws.cell(row=r, column=1, value="Total units").font = _LABEL_FONT
    ws.cell(row=r, column=2, value=summary.get("totalUnits") or len(units))
    r += 1
    ws.cell(row=r, column=1, value="Occupied").font = _LABEL_FONT
    ws.cell(row=r, column=2, value=summary.get("occupiedUnits"))
    r += 1
    if summary.get("totalMarketRent") is not None:
        ws.cell(row=r, column=1, value="Total market rent").font = _LABEL_FONT
        c = ws.cell(row=r, column=2, value=summary.get("totalMarketRent"))
        c.number_format = _MONEY
        r += 1
    if summary.get("totalActualRent") is not None:
        ws.cell(row=r, column=1, value="Total actual rent").font = _LABEL_FONT
        c = ws.cell(row=r, column=2, value=summary.get("totalActualRent"))
        c.number_format = _MONEY

    _autosize(ws, {1: 12, 2: 12, 3: 12, 4: 24, 5: 8,
                   6: 13, 7: 13, 8: 12, 9: 12})


# ---------------------------------------------------------------------------
# Public entrypoint
# ---------------------------------------------------------------------------

def build_workbook_bytes(
    prop: dict[str, Any],
    data: dict[str, Any],
    sources: dict[str, Any] | None,
) -> bytes:
    """Build the three-sheet deal workbook and return it as `.xlsx` bytes.

    `data` is the dict returned by `ui.exec_summary._build_summary_data`
    (deal, cf, verdict, cap/dscr/coc/ppu, lp_irr/project_irr/equity_multiple,
    tightened). `sources` is `load_sources(folder.path)` — used only for the
    rent-roll sheet, tolerated as None.
    """
    wb = Workbook()
    _build_summary_sheet(wb.active, prop, data)
    _build_returns_sheet(wb.create_sheet(), data)
    _build_rent_roll_sheet(wb.create_sheet(), sources)

    buf = BytesIO()
    wb.save(buf)
    return buf.getvalue()
