#!/usr/bin/env bash
# ===========================================================================
# Eight Rock Workbench v5.0 — one-shot installer for a fresh Ubuntu 24.04 box
# (Section 9.1 "Deployment reference — dedicated office server").
# ---------------------------------------------------------------------------
# Installs and wires: Python 3.12 + uv, PostgreSQL 16, Caddy (auto-HTTPS),
# UFW, the systemd service, and the pilot schema. Bind Streamlit to localhost;
# Caddy fronts the public side. Run as root (sudo) on the SERVER, not here.
#
#   sudo DOMAIN=workbench.eight-rock.com ADMIN_SSH_CIDR=203.0.113.4/32 \
#        APP_DIR=/opt/8rw ./deploy/install.sh
#
# Idempotent: safe to re-run. Prints a summary + next manual steps at the end.
# ===========================================================================
set -euo pipefail

DOMAIN="${DOMAIN:-workbench.eight-rock.com}"
APP_DIR="${APP_DIR:-/opt/8rw}"                 # LOCAL disk — never OneDrive (9.2)
DB_NAME="${DB_NAME:-workbench}"
DB_USER="${DB_USER:-workbench}"
ADMIN_SSH_CIDR="${ADMIN_SSH_CIDR:-}"           # e.g. your office IP; empty = allow SSH from anywhere (not recommended)
REPO_URL="${REPO_URL:-}"                        # optional: git URL to clone if APP_DIR is empty

log(){ printf '\n\033[1;33m▸ %s\033[0m\n' "$*"; }
[ "$(id -u)" -eq 0 ] || { echo "Run with sudo/root on the server." >&2; exit 1; }

# --- 1. Base packages -------------------------------------------------------
log "Installing base packages (Python 3.12, PostgreSQL 16, Caddy, UFW)…"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq python3.12 python3.12-venv postgresql-16 postgresql-contrib-16 \
    ufw curl git gnupg debian-keyring debian-archive-keyring apt-transport-https ca-certificates

# uv (astral) — system-wide
if ! command -v uv >/dev/null 2>&1; then
    curl -LsSf https://astral.sh/uv/install.sh | env UV_INSTALL_DIR=/usr/local/bin sh
fi

# Caddy official repo
if ! command -v caddy >/dev/null 2>&1; then
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' \
        | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' \
        > /etc/apt/sources.list.d/caddy-stable.list
    apt-get update -qq && apt-get install -y -qq caddy
fi

# --- 2. Service account + app dir ------------------------------------------
log "Creating service account and app directory ${APP_DIR}…"
id workbench >/dev/null 2>&1 || useradd -r -s /usr/sbin/nologin workbench
mkdir -p "$APP_DIR" /var/log/8rw /var/log/caddy
if [ -n "$REPO_URL" ] && [ ! -e "$APP_DIR/app.py" ]; then
    git clone "$REPO_URL" "$APP_DIR"
fi
chown -R workbench:workbench "$APP_DIR" /var/log/8rw

# --- 3. PostgreSQL ----------------------------------------------------------
log "Configuring PostgreSQL…"
pg_ctlcluster 16 main start 2>/dev/null || systemctl start postgresql || true
DB_PASS="$(openssl rand -hex 24)"
sudo -u postgres psql -v ON_ERROR_STOP=1 <<SQL || true
DO \$\$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='${DB_USER}') THEN
    CREATE ROLE ${DB_USER} LOGIN PASSWORD '${DB_PASS}';
  END IF;
END \$\$;
SELECT 'CREATE DATABASE ${DB_NAME} OWNER ${DB_USER}'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname='${DB_NAME}')\gexec
SQL
# Only print/store the freshly generated password if we created the role now.
if [ -f "$APP_DIR/.env" ] && grep -q '^DATABASE_URL=' "$APP_DIR/.env"; then
    log "Existing .env DATABASE_URL kept (not overwriting DB credentials)."
else
    umask 077
    cat > "$APP_DIR/.env" <<ENV
# Generated by deploy/install.sh — secrets, DO NOT COMMIT (Section 9.1).
DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@127.0.0.1:5432/${DB_NAME}
ER_STORAGE_BACKEND=local
ER_AUTH_BACKEND=oidc
APP_VERSION=v5.0-pilot
# ANTHROPIC_API_KEY=sk-ant-...   # optional; AI layer is opt-in (Section 11)
ENV
    chown workbench:workbench "$APP_DIR/.env"
fi

log "Applying pilot schema…"
DBURL="$(grep '^DATABASE_URL=' "$APP_DIR/.env" | cut -d= -f2-)"
sudo -u postgres psql "$DB_NAME" -f "$APP_DIR/db/pilot_schema.sql" >/dev/null

# --- 4. Python environment --------------------------------------------------
log "Installing Python dependencies via uv…"
sudo -u workbench bash -lc "cd '$APP_DIR' && uv sync --frozen" || \
sudo -u workbench bash -lc "cd '$APP_DIR' && uv sync"

# --- 5. systemd service -----------------------------------------------------
log "Installing systemd service…"
sed "s#/opt/8rw#${APP_DIR}#g" "$APP_DIR/deploy/workbench.service" > /etc/systemd/system/workbench.service
systemctl daemon-reload
systemctl enable --now workbench

# --- 6. Caddy ---------------------------------------------------------------
log "Configuring Caddy for ${DOMAIN}…"
sed "s/workbench.eight-rock.com/${DOMAIN}/g" "$APP_DIR/deploy/Caddyfile" > /etc/caddy/Caddyfile
systemctl enable caddy
systemctl reload caddy || systemctl restart caddy

# --- 7. Firewall ------------------------------------------------------------
log "Configuring UFW (public 80/443; 8501 stays localhost)…"
ufw allow 80/tcp
ufw allow 443/tcp
if [ -n "$ADMIN_SSH_CIDR" ]; then
    ufw allow from "$ADMIN_SSH_CIDR" to any port 22 proto tcp
else
    ufw allow 22/tcp   # WARNING: SSH open to the world — set ADMIN_SSH_CIDR
fi
ufw --force enable

# --- Done -------------------------------------------------------------------
log "Install complete."
cat <<DONE

  Workbench v5.0 pilot stack installed.
    Domain    : https://${DOMAIN}
    App dir   : ${APP_DIR}   (local disk — never OneDrive, Section 9.2)
    Service   : systemctl status workbench   |   journalctl -u workbench -f
    Proxy     : systemctl status caddy
    Database  : ${DB_NAME}  (credentials in ${APP_DIR}/.env — gitignored)

  MANUAL steps remaining:
    1. Point DNS A-record ${DOMAIN} -> this server's reserved public IP.
    2. Port-forward public 80 + 443 to this box on your router.
    3. Fill in the [auth] OIDC block in .streamlit/secrets.toml (Auth0/Entra, Section 9.4).
    4. Schedule deploy/backup.sh nightly (cron/systemd timer).
    5. First login auto-promotes to admin; approve subsequent users (FR-9.4.3).
DONE
