"""One-shot extractor: parse `knowledgebase/acquisition-checklist-*.html`
into a structured Python data module at `core/acquisition_checklist_default.py`.

Run:
    uv run python -m scripts.extract_acquisition_checklist

Re-run after editing the source HTML to regenerate the committed data module.
"""

from __future__ import annotations

import sys
from pathlib import Path
from textwrap import dedent

from bs4 import BeautifulSoup

WORKBENCH_ROOT = Path(__file__).resolve().parents[2]
HTML_SOURCE = WORKBENCH_ROOT / "knowledgebase" / "acquisition-checklist-04282026.html"
OUTPUT = WORKBENCH_ROOT / "python_workbench" / "core" / "acquisition_checklist_default.py"


def _slugify(s: str) -> str:
    out = []
    last_dash = False
    for ch in s.lower():
        if ch.isalnum():
            out.append(ch); last_dash = False
        elif not last_dash and out:
            out.append("-"); last_dash = True
    return "".join(out).strip("-")[:40]


def parse() -> list[dict]:
    if not HTML_SOURCE.is_file():
        raise FileNotFoundError(f"Source HTML not found: {HTML_SOURCE}")
    soup = BeautifulSoup(HTML_SOURCE.read_text(encoding="utf-8"), "lxml")
    phases: list[dict] = []

    for block in soup.select("div.phase-block"):
        phase_id = block.get("id", "")
        header = block.select_one(".phase-header")
        number = (header.select_one(".phase-number").get_text(strip=True) if header else "")
        info = header.select_one(".phase-info") if header else None
        tag = (info.select_one(".phase-tag").get_text(strip=True) if info else "")
        title = (info.select_one(".phase-title").get_text(strip=True) if info else "")
        timeline = (info.select_one(".phase-timeline").get_text(strip=True) if info else "")
        summary_el = block.select_one(".phase-summary")
        summary = (summary_el.get_text(" ", strip=True) if summary_el else "")

        categories: list[dict] = []
        for cat in block.select(".category"):
            label_el = cat.select_one(".category-label")
            label = (label_el.get_text(strip=True) if label_el else "")
            cat_slug = _slugify(label)

            items: list[dict] = []
            for i, li in enumerate(cat.select(".checklist > li"), start=1):
                critical = "critical" in (li.get("class") or [])
                text_el = li.select_one(".item-text")
                # Clone, extract note before grabbing text, so item_text doesn't include note
                note = ""
                if text_el:
                    note_el = text_el.select_one(".item-note")
                    if note_el:
                        note = note_el.get_text(" ", strip=True)
                        note_el.decompose()
                    text = text_el.get_text(" ", strip=True)
                else:
                    text = ""

                deadline_el = li.select_one(".deadline")
                deadline_text = (deadline_el.get_text(strip=True) if deadline_el else "")
                deadline_classes = (deadline_el.get("class") or []) if deadline_el else []
                deadline_type = "open"
                for cls in deadline_classes:
                    if cls in ("hard", "soft", "open"):
                        deadline_type = cls
                        break

                item_id = f"{phase_id}-{cat_slug}-{i:02d}"
                items.append({
                    "id": item_id,
                    "text": text,
                    "note": note,
                    "deadline_text": deadline_text,
                    "deadline_type": deadline_type,
                    "critical": critical,
                })
            categories.append({"label": label, "items": items})

        phases.append({
            "id": phase_id,
            "number": number,
            "tag": tag,
            "title": title,
            "timeline": timeline,
            "summary": summary,
            "categories": categories,
        })
    return phases


def _py_str(s: str) -> str:
    """Render a string as a Python literal. Multi-line uses triple-quote."""
    if not s:
        return '""'
    if "\n" in s or len(s) > 100:
        # triple-quoted with escaped triple-quotes
        body = s.replace('"""', '\\"\\"\\"')
        return f'"""{body}"""'
    escaped = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def emit(phases: list[dict]) -> str:
    """Render the parsed structure as a Python module."""
    lines: list[str] = []
    lines.append('"""Default Acquisition Checklist catalog.\n')
    lines.append("AUTO-GENERATED by `scripts/extract_acquisition_checklist.py`")
    lines.append("from `knowledgebase/acquisition-checklist-04282026.html`.\n")
    lines.append("Do not edit by hand — re-run the extractor after editing the source HTML.\n")
    lines.append('"""\n')
    lines.append("from __future__ import annotations\n")
    lines.append("from dataclasses import dataclass, field\n")
    lines.append("\n")
    lines.append("@dataclass(frozen=True)")
    lines.append("class Item:")
    lines.append("    id: str")
    lines.append("    text: str")
    lines.append("    note: str")
    lines.append("    deadline_text: str")
    lines.append('    deadline_type: str  # "hard" | "soft" | "open"')
    lines.append("    critical: bool")
    lines.append("\n")
    lines.append("@dataclass(frozen=True)")
    lines.append("class Category:")
    lines.append("    label: str")
    lines.append("    items: tuple[Item, ...]")
    lines.append("\n")
    lines.append("@dataclass(frozen=True)")
    lines.append("class Phase:")
    lines.append("    id: str")
    lines.append("    number: str")
    lines.append("    tag: str")
    lines.append("    title: str")
    lines.append("    timeline: str")
    lines.append("    summary: str")
    lines.append("    categories: tuple[Category, ...]")
    lines.append("\n")
    lines.append("\n")
    lines.append("ACQUISITION_CHECKLIST: tuple[Phase, ...] = (")
    for phase in phases:
        lines.append("    Phase(")
        lines.append(f"        id={_py_str(phase['id'])},")
        lines.append(f"        number={_py_str(phase['number'])},")
        lines.append(f"        tag={_py_str(phase['tag'])},")
        lines.append(f"        title={_py_str(phase['title'])},")
        lines.append(f"        timeline={_py_str(phase['timeline'])},")
        lines.append(f"        summary={_py_str(phase['summary'])},")
        lines.append("        categories=(")
        for cat in phase["categories"]:
            lines.append("            Category(")
            lines.append(f"                label={_py_str(cat['label'])},")
            lines.append("                items=(")
            for item in cat["items"]:
                lines.append("                    Item(")
                lines.append(f"                        id={_py_str(item['id'])},")
                lines.append(f"                        text={_py_str(item['text'])},")
                lines.append(f"                        note={_py_str(item['note'])},")
                lines.append(f"                        deadline_text={_py_str(item['deadline_text'])},")
                lines.append(f"                        deadline_type={_py_str(item['deadline_type'])},")
                lines.append(f"                        critical={item['critical']!r},")
                lines.append("                    ),")
            lines.append("                ),")
            lines.append("            ),")
        lines.append("        ),")
        lines.append("    ),")
    lines.append(")")
    lines.append("")
    lines.append("")
    lines.append("def all_items() -> tuple[Item, ...]:")
    lines.append('    """Flatten the catalog to a single tuple of items."""')
    lines.append("    out: list[Item] = []")
    lines.append("    for phase in ACQUISITION_CHECKLIST:")
    lines.append("        for cat in phase.categories:")
    lines.append("            out.extend(cat.items)")
    lines.append("    return tuple(out)")
    lines.append("")
    lines.append("")
    lines.append("def find_item(item_id: str) -> Item | None:")
    lines.append('    """Look up an item by its stable id. Returns None if not found."""')
    lines.append("    for item in all_items():")
    lines.append("        if item.id == item_id:")
    lines.append("            return item")
    lines.append("    return None")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    phases = parse()
    n_items = sum(len(c["items"]) for p in phases for c in p["categories"])
    n_cats = sum(len(p["categories"]) for p in phases)
    print(f"Parsed {len(phases)} phases, {n_cats} categories, {n_items} items.")

    output = emit(phases)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(output, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(WORKBENCH_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
