"""Exec Summary tab — preview block + LLM-powered Artifact Engine panel.

Renders, in order:

  1. **Preview** — the workbench's verdict (GO / WATCH / NO-GO) + headline
     metrics + rationale, using DealState/sources read from the property
     folder. Always-on, no API calls.

  2. **Artifact Engine** (`_render_artifact_engine_panel`) — the five
     LLM-generated documents (Executive Summary, Investor Memo Trust-First,
     Investor Memo Sophisticated, Value-Add Strategy, LOI). Each generates
     end-to-end via Claude using the full deal briefing + Eight Rock's
     underwriting playbook (memory files), then renders into Eight Rock-
     branded Word docs via `core/markdown_to_docx.py`. Saved directly into
     the property folder alongside RR/T-12.

History: a deterministic Python-built 5-page DOCX export lived here through
v0.84. It was retired in v0.85 — programmatic templating cannot match the
analytical depth the LLM-driven artifacts produce, and having two competing
exports was confusing. Page-builder helpers (`_page1`..`_page5`),
`_build_docx`, the DOCX styling primitives, and the brand-color/logo
constants used solely by them have been removed.
"""

from __future__ import annotations

import datetime as dt
from pathlib import Path
from typing import Any

import streamlit as st

import config
from core.calc import DebtTerms, build_cashflow, build_debt_schedule
from core.irr import equity_multiple, lp_irr, project_irr
from core.sensitivity import SensitivityBase, build_sensitivity
from core.verdict import evaluate
from core.waterfall import run_waterfall
from data.property_io import (
    DealState,
    PropertyFolder,
    load_deal,
    load_sources,
)
from ui.components import section_card

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _derive_year1(deal: DealState, sources: dict[str, Any] | None) -> tuple[float, float]:
    if sources:
        rev = sources.get("totalRevenue")
        opex = sources.get("totalOpex")
        if rev and opex:
            try:
                rev_v = rev.get("value") if isinstance(rev, dict) else rev
                opex_v = opex.get("value") if isinstance(opex, dict) else opex
                if rev_v and opex_v:
                    return float(rev_v), float(opex_v)
            except (AttributeError, TypeError, ValueError):
                pass
    er = config.EXPENSE_RATIOS.get("C", 0.45)
    vac = deal.vacancy_frac
    denom = (1.0 - vac - er)
    gpr = deal.noi / denom if denom > 0 else deal.noi / 0.5
    return gpr, gpr * er


def _save_api_key_to_env(env_path: Path, key: str) -> None:
    """Write `ANTHROPIC_API_KEY=<key>` into the workbench's local `.env`.

    Preserves any other lines already in the file (e.g. future settings).
    If a `ANTHROPIC_API_KEY=` line already exists it gets replaced rather
    than duplicated. Atomic via tempfile + replace so a crash mid-write
    can't corrupt the file.
    """
    import re as _re
    import tempfile as _tempfile

    new_line = f"ANTHROPIC_API_KEY={key}"
    if env_path.is_file():
        existing = env_path.read_text(encoding="utf-8")
        if _re.search(r"^\s*ANTHROPIC_API_KEY\s*=", existing, _re.M):
            new_content = _re.sub(
                r"^\s*ANTHROPIC_API_KEY\s*=.*$",
                new_line,
                existing,
                flags=_re.M,
            )
        else:
            new_content = existing.rstrip("\n") + "\n" + new_line + "\n"
    else:
        new_content = (
            "# Eight Rock Workbench — local secrets (gitignored).\n"
            "# Generated by the in-app setup flow.\n"
            f"{new_line}\n"
        )

    env_path.parent.mkdir(parents=True, exist_ok=True)
    with _tempfile.NamedTemporaryFile(
        mode="w", encoding="utf-8", dir=str(env_path.parent),
        delete=False, suffix=".tmp",
    ) as tmp:
        tmp.write(new_content)
        tmp_path = Path(tmp.name)
    tmp_path.replace(env_path)


def _money(v: Any) -> str:
    if v is None:
        return "—"
    try:
        return f"${float(v):,.0f}"
    except (TypeError, ValueError):
        return str(v)


def _pct(v: Any, decimals: int = 2) -> str:
    if v is None:
        return "—"
    try:
        return f"{float(v) * 100:.{decimals}f}%"
    except (TypeError, ValueError):
        return str(v)


# DOCX-styling helpers and per-page builders that powered the legacy
# `_build_docx` deterministic export were retired in v0.85 along with
# the export itself. The Artifact Engine (LLM-driven, in
# `core/artifact_engine.py` + `core/markdown_to_docx.py`) is the sole
# document-generation path now.


def _build_summary_data(prop: dict[str, Any], folder: PropertyFolder | None):
    if folder is None:
        return None
    deal = load_deal(folder.path)
    if deal is None:
        return None
    sources = load_sources(folder.path)
    gpr, expenses = _derive_year1(deal, sources)

    debt_terms = DebtTerms(
        loan_amount=deal.loan_amount,
        annual_rate=deal.interest_rate,
        amort_months=config.AMORT_MONTHS,
        io_years=deal.io,
    )
    debt_sched = build_debt_schedule(debt_terms, deal.hp)
    cf = build_cashflow(
        year1_gpr=gpr,
        year1_vacancy_pct=deal.vacancy_frac,
        year1_expenses=expenses,
        rent_growth=deal.rent_growth,
        expense_growth=deal.expense_growth,
        am_fee_pct=deal.am_fee_pct,
        debt=debt_sched,
        hold_years=deal.hp,
        exit_cap=deal.exit_cap,
        equity_raise=deal.equity_raise,
    )
    pots = [r.cash_flow for r in cf.rows[:-1]] + [
        cf.rows[-1].cash_flow + cf.exit_proceeds_net
    ]
    wf = run_waterfall(equity_raise=deal.equity_raise, annual_pots=pots)
    lp_rate = lp_irr(wf.lp_cashflows)
    proj_rate = project_irr(
        equity_raise=deal.equity_raise,
        annual_cashflows=[r.cash_flow for r in cf.rows],
        exit_proceeds_net=cf.exit_proceeds_net,
    )
    em = equity_multiple(deal.equity_raise, wf.total_lp_distributions)
    cap = deal.noi / deal.pp if deal.pp else 0.0
    ads = debt_sched.annual_payment[0]
    dscr_v = (deal.noi - deal.am_fee_pct * gpr) / ads if ads else 0.0
    coc = cf.rows[0].coc
    ppu = deal.pp / (prop.get("units") or 1)

    verdict = evaluate(
        cap=cap, dscr=dscr_v, coc=coc, ppu=ppu,
        city=prop.get("city") or "",
    )

    # Sensitivity grid
    sens_base = SensitivityBase(
        purchase_price=deal.pp,
        year1_gpr=gpr, year1_expenses=expenses,
        am_fee_pct=deal.am_fee_pct,
        loan_amount=deal.loan_amount,
        annual_rate=deal.interest_rate,
        amort_months=config.AMORT_MONTHS, io_years=deal.io,
        hold_years=deal.hp, exit_cap=deal.exit_cap,
        equity_raise=deal.equity_raise,
    )
    sens = build_sensitivity(sens_base)

    # ---- Module E (§6.3): named stress overlays + QA + DD tightening -----
    from core import verdict_tightening
    from core.extraction_qa import run_qa
    from core.stress_overlays import run_stress_overlays

    stress = run_stress_overlays(
        sens_base,
        base_vacancy=deal.vacancy_frac,
        base_rent_growth=deal.rent_growth,
        base_expense_growth=deal.expense_growth,
    )
    qa_report = run_qa(sources or {})

    # DD only tightens once diligence has actually started (dd.json exists);
    # bootstrapping a 0%-complete file here would demote every fresh deal.
    dd_state = None
    if (folder.path / "dd.json").is_file():
        from core import due_diligence as dd_mod
        dd_state = dd_mod.recompute_aggregates(dd_mod.load_state(folder.path))

    tight = verdict_tightening.tighten(
        verdict, dd_state=dd_state, stress=stress, qa=qa_report)

    return {
        "deal": deal, "sources": sources, "cf": cf, "wf": wf,
        "lp_irr": lp_rate, "project_irr": proj_rate, "equity_multiple": em,
        "cap": cap, "dscr": dscr_v, "coc": coc, "ppu": ppu,
        "ads": ads, "gpr_y1": gpr, "expenses_y1": expenses,
        "verdict": verdict, "sensitivity": sens,
        "stress": stress, "qa": qa_report, "tightened": tight,
        "dd_started": dd_state is not None,
    }


# 5-page deterministic builder (_page1.._page5 + _build_docx) was retired
# in v0.85 — superseded by the LLM-powered Artifact Engine.




# ---------------------------------------------------------------------------
# Streamlit renderer
# ---------------------------------------------------------------------------

def render_exec_summary(
    prop: dict[str, Any],
    folder: PropertyFolder | None,
) -> None:
    c = config.COLORS

    if folder is None:
        st.info(
            "No property folder yet. Open the Underwriting tab and adjust "
            "sliders to create a deal first."
        )
        return

    data = _build_summary_data(prop, folder)
    if data is None:
        st.info("No saved underwriting yet. Open the Underwriting tab and adjust the sliders to create one.")
        return

    deal = data["deal"]
    verdict = data["verdict"]

    # Brian 5/29 v2.0.20:
    #  • "Preview" section renamed to "{name} — Executive Summary".
    #  • The duplicate "### {name} — Executive Summary" markdown line
    #    below was Brian's "remove duplicate text" call — gone.
    #  • 5-Year Cash Flow MOVED to the very top of this tab (above the
    #    headline + recommendation block), per Brian's screenshot. It's
    #    the canonical "what does the deal look like over the hold" view
    #    and belongs in the summary narrative.
    from ui.underwriting import _render_cashflow_table
    from data.property_io import load_sources
    sources_for_cf = load_sources(folder.path) if folder is not None else None
    units_for_cf = prop.get("units")
    city_for_cf = prop.get("city")
    with section_card("5-Year Cash Flow", icon="💵"):
        _render_cashflow_table(deal, sources_for_cf, units_for_cf, city=city_for_cf)

    exec_summary_title = f"{prop.get('name', '—')} — Executive Summary"
    with section_card(exec_summary_title):
        color_map = {
            "GO": c["gn"], "WATCH": c["yw"],
            "FINANCING-CONSTRAINED-WATCH": c["yw"], "NO-GO": c["rd"],
        }
        tight = data.get("tightened")
        shown_verdict = tight.verdict if tight is not None else verdict.verdict
        fg = color_map.get(shown_verdict, c["tx2"])
        st.markdown(
            f"**Recommendation:** "
            f"<span style='color:{fg};font-weight:700;font-size:18px'>{shown_verdict}</span>",
            unsafe_allow_html=True,
        )
        if tight is not None and tight.downgraded:
            base_fg = color_map.get(tight.base_verdict, c["tx2"])
            st.markdown(
                f"<span style='color:{c['tx2']};font-size:13px'>Economics alone "
                f"read <b style='color:{base_fg}'>{tight.base_verdict}</b> — "
                "downgraded by the findings below (§6.3 tightening).</span>",
                unsafe_allow_html=True,
            )

        st.markdown("**Key metrics:**")
        st.markdown(
            f"- Asking price: **{_money(deal.pp)}**\n"
            f"- Price per unit: **{_money(data['ppu'])}**\n"
            f"- Cap rate: **{_pct(data['cap'])}**\n"
            f"- DSCR: **{data['dscr']:.2f}x**\n"
            f"- Cash-on-cash (Y1): **{_pct(data['coc'])}**\n"
            f"- LP IRR: **{_pct(data['lp_irr'])}** (target ≥ {config.LP_IRR_TARGET*100:.0f}%)\n"
            f"- Project IRR: **{_pct(data['project_irr'])}** (target ≥ {config.PROJECT_IRR_TARGET*100:.0f}%)\n"
            f"- LP Equity Multiple: **{data['equity_multiple']:.2f}x** (target ≥ {config.LP_EQUITY_MULTIPLE_TARGET:.1f}x)"
        )

        st.markdown("**Rationale:**")
        for r in verdict.rationale:
            st.markdown(f"- {r}")
        if tight is not None:
            for r in tight.rationale:
                st.markdown(f"- ⚠️ {r}")
            if not data.get("dd_started"):
                st.caption("Due diligence not started yet — the verdict above "
                           "is economics-only and will tighten as DD findings land.")

    _render_stress_panel(data)

    # ---- Excel export (deterministic, no-API) ----
    # Brian's first-user feedback (2026-08): investors want the *numbers* in a
    # spreadsheet they can slice, not just the Artifact Engine's Word prose.
    # Built straight from the same DealState + cash-flow projection shown above
    # so the download always matches the screen. Bytes built lazily inside the
    # section so a bad `sources` block can't blank the whole tab.
    with section_card("Download to Excel", icon="⬇"):
        try:
            from core.excel_export import build_workbook_bytes
            xlsx_bytes = build_workbook_bytes(prop, data, data.get("sources"))
            safe_name = (prop.get("name") or "deal").replace(" ", "_")
            st.download_button(
                label="⬇ Download Excel (Summary · Returns · Rent Roll)",
                data=xlsx_bytes,
                file_name=f"{safe_name}_underwriting.xlsx",
                mime=(
                    "application/vnd.openxmlformats-"
                    "officedocument.spreadsheetml.sheet"
                ),
                key="dl_excel_summary",
                use_container_width=True,
            )
            st.caption(
                "Three sheets — Summary, Returns (5-year cash flow + exit), "
                "and Rent Roll — pulled from this deal's saved underwriting."
            )
        except Exception as e:  # noqa: BLE001
            st.error(f"Excel export unavailable: {e}")

    # ---- Artifact Engine (LLM-powered analytical generators) ----
    # Per Brian 2026-05-08: the Exec Summary tab's only document-export
    # surface is the Artifact Engine. The previous "Quick deterministic
    # export" — a programmatic Python-built 5-page DOCX — was retired in
    # v0.85: programmatic templating cannot match the analytical depth
    # the LLM-driven artifacts produce, and having two competing exports
    # was confusing. If you need a no-API summary, the Verdict + Preview
    # block above shows the headline GO/WATCH/NO-GO with rationale.
    _render_artifact_engine_panel(prop, data, folder)


def _render_stress_panel(data: dict[str, Any]) -> None:
    """Module E (§6.3): the three named stress overlays, each a row with the
    stressed LP IRR, the delta from base, and a pass/fail chip."""
    stress = data.get("stress")
    if stress is None or not stress.results:
        return
    c = config.COLORS
    with section_card(
        "Named Stress Tests",
        icon="🌪",
        subtitle=(
            "The deal re-run under three named historical scenarios. A failure "
            f"means LP IRR falls below the {config.SENSITIVITY_LP_IRR_FLAG:.0%} "
            "downside bar — a failed scenario holds a GO at WATCH."
        ),
    ):
        for r in stress.results:
            if r.lp_irr is None:
                lp_txt = "capital not returned"
            else:
                lp_txt = f"LP IRR {r.lp_irr * 100:.1f}%"
            delta_txt = (f" ({r.lp_irr_delta * 100:+.1f} pts vs base)"
                         if r.lp_irr_delta is not None else "")
            if r.failed:
                chip = (f"<span style='color:{c['rd']};font-weight:700'>FAIL</span>")
            else:
                chip = (f"<span style='color:{c['gn']};font-weight:700'>PASS</span>")
            st.markdown(
                f"{chip} &nbsp;**{r.overlay.label}** — {lp_txt}{delta_txt}",
                unsafe_allow_html=True,
            )
            st.caption(r.overlay.description)


def _render_artifact_engine_panel(
    prop: dict[str, Any],
    data: dict[str, Any],
    folder: PropertyFolder | None,
) -> None:
    """Five-artifact generation panel. Each artifact is its own row with a
    Generate button + a list of previously-generated files (download +
    open-folder). Reads ANTHROPIC_API_KEY from env / .env.

    Generated docs save directly into the property folder alongside RR/T-12
    per Brian's instruction (no `Generated/` subfolder).
    """
    c = config.COLORS
    from core.ai_gate import AIDisabled
    from core.artifact_engine import (
        ARTIFACT_CATALOG,
        ArtifactGenerationError,
        generate_artifact,
        list_generated_artifacts,
    )

    with section_card(
        "Artifact Engine — LLM-Generated Deal Documents",
        icon="🪄",
        accent="ac",
        subtitle=(
            "Each artifact is generated from scratch using the workbench's "
            "full deal data (rent roll, T-12, comps, market context, sensitivity) "
            "plus Eight Rock's underwriting playbook. Saves as MS Word "
            "alongside other property docs."
        ),
    ):
        if folder is None:
            st.info(
                "This property has no folder yet. Upload a document or save "
                "the deal in Underwriting to create the folder."
            )
            return

        # API key check — degrade gracefully with an actionable setup
        # message. By this point `app.py` has already called load_dotenv at
        # startup; we re-attempt here as a safety net in case the user just
        # created `.env` mid-session and reloaded the tab.
        import os as _os
        if not _os.environ.get("ANTHROPIC_API_KEY"):
            try:
                from dotenv import load_dotenv
                load_dotenv(Path(__file__).resolve().parent.parent / ".env")
            except ImportError:
                pass
        api_key_present = bool(_os.environ.get("ANTHROPIC_API_KEY"))
        if not api_key_present:
            # In-app setup flow (Brian flagged the terminal-instructions
            # version was annoying). Paste key → click Save → workbench
            # writes to `python_workbench/.env`, reloads, artifacts unlock.
            env_path = Path(__file__).resolve().parent.parent / ".env"

            st.warning(
                "⚠️ **Anthropic API key needed to generate artifacts.** "
                "Get one at "
                "[console.anthropic.com/settings/keys]"
                "(https://console.anthropic.com/settings/keys) → "
                "**Create Key** → copy it (it is shown only once). Paste it "
                "below and click Save — it stores in a local gitignored "
                "`.env` file. You'll only do this once.\n\n"
                "Note: API usage is billed separately from a Claude.ai or "
                "Claude Code subscription, so the console account needs "
                "credits on it."
            )
            with st.form("api_key_setup_form", clear_on_submit=False):
                col_in, col_btn = st.columns([4, 1])
                with col_in:
                    new_key = st.text_input(
                        "Anthropic API key",
                        type="password",
                        placeholder="sk-ant-api...",
                        label_visibility="collapsed",
                        key="api_key_setup_input",
                    )
                with col_btn:
                    submitted = st.form_submit_button(
                        "💾 Save & enable",
                        type="primary",
                        use_container_width=True,
                    )
                if submitted:
                    cleaned = (new_key or "").strip()
                    if not cleaned:
                        st.error("Paste a key first.")
                    elif cleaned.startswith("sk-ant-oat"):
                        st.error(
                            "That's a Claude Code **OAuth token**, not an API "
                            "key — it won't work here. Create an API key at "
                            "[console.anthropic.com/settings/keys]"
                            "(https://console.anthropic.com/settings/keys); "
                            "it looks like `sk-ant-api...`."
                        )
                    elif not cleaned.startswith("sk-"):
                        st.error(
                            "That doesn't look like an Anthropic key — they "
                            "start with `sk-ant-`. Get one at "
                            "[console.anthropic.com/settings/keys]"
                            "(https://console.anthropic.com/settings/keys) → "
                            "Create Key."
                        )
                    else:
                        try:
                            _save_api_key_to_env(env_path, cleaned)
                            _os.environ["ANTHROPIC_API_KEY"] = cleaned
                            st.success(
                                "✓ Saved! Artifacts are now enabled. "
                                "Reloading…"
                            )
                            st.rerun()
                        except OSError as e:
                            st.error(f"Could not write to `{env_path}`: {e}")

            st.caption(
                f"Saves to `{env_path}`. The deterministic Preview block "
                "above works without a key — only LLM-generated artifacts "
                "need it."
            )

        # Existing files map (so we can show "last generated" + downloads)
        existing = list_generated_artifacts(folder)

        # Per-artifact rows
        for spec in ARTIFACT_CATALOG:
            row_files = existing.get(spec.type_id, [])
            last_label = (
                f"last: {dt.datetime.fromtimestamp(row_files[0].stat().st_mtime).strftime('%b %d, %Y %I:%M %p')}"
                if row_files
                else "— never —"
            )

            col_btn, col_meta = st.columns([1, 3])
            with col_btn:
                gen_clicked = st.button(
                    f"{spec.icon} Generate",
                    key=f"art_gen_{spec.type_id}",
                    type="primary" if spec.enabled else "secondary",
                    disabled=(not spec.enabled or not api_key_present),
                    use_container_width=True,
                    help=(
                        spec.description if spec.enabled
                        else f"{spec.label} — coming next release."
                    ),
                )
            with col_meta:
                enabled_badge = (
                    f"<span style='color:{c['gn']};font-weight:700'>● ready</span>"
                    if spec.enabled
                    else f"<span style='color:{c['tx3']};font-weight:600'>○ coming soon</span>"
                )
                st.markdown(
                    f"<div style='font-size:14px;color:{c['tx']};font-weight:600'>"
                    f"{spec.icon} {spec.label} &nbsp; {enabled_badge}</div>"
                    f"<div style='font-size:11px;color:{c['tx2']};margin-top:2px'>"
                    f"{spec.description}</div>"
                    f"<div style='font-size:11px;color:{c['tx3']};margin-top:2px'>"
                    f"{last_label}</div>",
                    unsafe_allow_html=True,
                )

            if gen_clicked and spec.enabled and api_key_present:
                from data.property_io import load_deal as _load_deal
                _data = _load_deal(folder.path)
                if _data is None:
                    st.error(
                        "No saved underwriting yet. Open the Underwriting "
                        "tab and adjust the dials to create one."
                    )
                else:
                    deal = _data
                    with st.spinner(
                        f"Generating {spec.label} via Claude Opus… "
                        "(30-60 seconds — analyzing rent roll, T-12, comps, "
                        "and applying playbook)"
                    ):
                        try:
                            saved_path = generate_artifact(
                                artifact_type=spec.type_id,
                                prop=prop,
                                deal=deal,
                                folder=folder,
                            )
                            st.success(
                                f"✓ Saved `{saved_path.name}` to "
                                f"`{folder.folder_name}/`"
                            )
                            st.rerun()
                        except AIDisabled as e:
                            # AC-11.2: offer the fallback rather than failing.
                            st.info(
                                f"**{e.surface} is turned off for this "
                                f"organization.** {e.fallback}", icon="🛈")
                        except ArtifactGenerationError as e:
                            st.error(f"Generation failed: {e}")
                        except Exception as e:  # noqa: BLE001
                            st.error(f"Unexpected error: {e}")

            # File list for this artifact type (show downloads of past gens)
            if row_files:
                with st.expander(
                    f"📂 {len(row_files)} saved {spec.label.lower()} file(s)",
                    expanded=False,
                ):
                    for fpath in row_files:
                        size_kb = fpath.stat().st_size / 1024
                        size_str = (
                            f"{size_kb:,.0f} KB"
                            if size_kb < 1024
                            else f"{size_kb/1024:,.1f} MB"
                        )
                        cdl1, cdl2 = st.columns([4, 1])
                        with cdl1:
                            st.markdown(
                                f"📄 `{fpath.name}` · {size_str} · "
                                f"{dt.datetime.fromtimestamp(fpath.stat().st_mtime).strftime('%Y-%m-%d %I:%M %p')}"
                            )
                        with cdl2:
                            try:
                                file_bytes = fpath.read_bytes()
                                st.download_button(
                                    label="⬇",
                                    data=file_bytes,
                                    file_name=fpath.name,
                                    mime=(
                                        "application/vnd.openxmlformats-"
                                        "officedocument.wordprocessingml.document"
                                    ),
                                    key=f"dl_{spec.type_id}_{fpath.name}",
                                    use_container_width=True,
                                )
                            except OSError:
                                st.caption("⚠ file read error")

            st.markdown(
                f'<hr style="border:0;border-top:1px solid {c["bdr"]};margin:8px 0">',
                unsafe_allow_html=True,
            )
